### ISSUE TITLE
Error setting up entry BRC1H for daikin_madoka with new HA version

### ISSUE THREAD

**Issue by pacomm** [mduran80/daikin_madoka#21]
Logger: homeassistant.config_entries
Source: custom_components/daikin_madoka/__init__.py:66
Integration: Daikin Madoka
First occurred: 13:09:13 (1 occurrences)
Last logged: 13:09:13

Error setting up entry BRC1H for daikin_madoka
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/daikin_madoka/__init__.py", line 66, in async_setup_entry
    await discover_devices(
  File "/usr/local/lib/python3.10/site-packages/pymadoka/connection.py", line 56, in discover_devices
    DISCOVERED_DEVICES_CACHE = await scanner.get_discovered_devices()
AttributeError: 'HaBleakScannerWrapper' object has no attribute 'get_discovered_devices'

**Comment by rawframe** [comment]
### Updated to:

Home Assistant 2022.10.1
Supervisor 2022.09.1
Operating System 9.0
Frontend 20221006.0 - latest

### **_Stopped working so I tried:_**

1. Unpaired all bluetooth pairings, then rebooted.
2. Deleted Madoka software from custom_components, then rebooted.
3. Re-installed Madoka software to custom_components, then rebooted.
4. Paired Madoka with HCI0 default bluetooth adapter successfully, then rebooted. (Checked hci0 was correct).
5. Added Madoka integration in HA.
6. **Entered mac address but it always FAILS.** 

What are the ticks are for?
What is the number 5 at the bottom for?
Tried turning ticks on and off and entering  only one mac address in lower case, upper case, and in quotes ('') but nothing works.
Tried disabling HA bluetooth integration also.

### **_Can you please help_**, has been great for many years, I need this software to work!

**Comment by mduran80** [comment]
Fixed in the last version.

See https://github.com/mduran80/daikin_madoka/issues/22

**Comment by rawframe** [comment]
### **Thank you!!**

Just as a note:
1. Sometimes the polling fails, so temperature or manual controller changes fail to update status.
2. Newer HA versions where bluetooth is upgraded, sometimes Madoka devices all have the same name which is just the bluetooth adapter part name and not the actual controller name.

A restart usually fixes these issues.
