### ISSUE TITLE
Lose connection with madoka, need to disable and enable again the integration

### ISSUE THREAD

**Issue by Dodofox** [mduran80/daikin_madoka#35]
Hello :) 

First thanks for your job, it's amazing. 

I just change my hardware which runs home assistant (migration from raspberry pi3 to odroid N2+). I'm running the latest release of HA. 

Since I migrated on this hardware, the daikin_madoka integration is not able to maintain connection during long time. Sometimes the module become unavailable and the only thing I have in the log is : 

```Logger: homeassistant.helpers.integration_platform
Source: loader.py:855
First occurred: 17:33:07 (2 occurrences)
Last logged: 17:39:21

Unexpected error importing daikin_madoka/cast.py
Unexpected error importing daikin_madoka/hardware.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 50, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 838, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 855, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.daikin_madoka-main.cast'

```

When I try to reboot, the home assistant can't boot properly because it's waiting for daikin_madoka integration. I have to disable-it, then hard reboot, enable-it again and soft reboot to retrieve all functionality. 
Today it appeared twice. I'm not really understand what is happening. 

If you need more information please ask.

Best regards,

Dorian

**Comment by Dodofox** [comment]
After restart I Have following error but that seems work (until I hit the problem mentionned above)

```
Logger: homeassistant.helpers.integration_platform
Source: loader.py:855
First occurred: 17:58:25 (9 occurrences)
Last logged: 18:01:01

Unexpected error importing daikin_madoka/logbook.py
Unexpected error importing daikin_madoka/group.py
Unexpected error importing daikin_madoka/system_health.py
Unexpected error importing daikin_madoka/cast.py
Unexpected error importing daikin_madoka/hardware.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 50, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 838, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 855, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.daikin_madoka-main.significant_change'
```

**Comment by mduran80** [comment]
I will try to have a look at it in the weekend, in order to let HA boot
without daikin_madoka blocking.

Regarding the unstable connections, are you using an external adapter?
Connection losses could be related to low power or range

**Comment by Dodofox** [comment]
Hello,

I don't know if it's related to power, but in fact that look there is a problem with bluetooth, (I can see it as paired but not connected).

I'm using bluetooth dongle. I will open a case on bluetooth addon.

The last error I have when its fail is 

```
Logger: pymadoka.connection
Source: runner.py:186
First occurred: 08:42:17 (1088 occurrences)
Last logged: 09:00:32

[org.bluez.Error.Failed] Operation already in progress
[org.bluez.Error.Failed] br-connection-canceled
```

**Comment by rawframe** [comment]
Hi, I too have the same issue and for many years.

```
Logger: pymadoka.connection
Source: runner.py:186
First occurred: 04:59:41 (57297 occurrences)
Last logged: 10:39:01

No backend with an available connection slot that can reach address XX:XX:XX:XX:XX:XX was found
[org.bluez.Error.Failed] Operation already in progress
[org.bluez.Error.Failed] br-connection-canceled
'str' object has no attribute 'name'
```
We use RP3b and the integrated bluetooth. The only time this has worked without needing constant reloads was about 1 year ago but I was not sure if it was to do with the underlying OS or HA.
This is problem makes the whole integration unusable which is a shame given the effort the creator put into it.

Have you found the problem and solution? Thanks

**Comment by rawframe** [comment]
here is fuller log
```
2023-11-04 23:32:48.078 DEBUG (MainThread) [pymadoka.connection] Forcing disconnect...
2023-11-04 23:32:59.576 DEBUG (MainThread) [pymadoka.connection] Forcing disconnect...
2023-11-04 23:33:02.108 DEBUG (MainThread) [pymadoka.connection] Forcing disconnect...
2023-11-04 23:33:03.077 DEBUG (MainThread) [pymadoka.connection] Forcing disconnect...
2023-11-04 23:33:07.434 DEBUG (MainThread) [pymadoka.connection] Starting connection manager on 1C:XX:XX:XX:XX:XX
2023-11-04 23:33:07.435 DEBUG (MainThread) [pymadoka.connection] Bluetooh LE hardware warming up...
2023-11-04 23:33:18.122 INFO (MainThread) [pymadoka.connection] Connected to 1C:XX:XX:XX:XX:XX
2023-11-04 23:33:20.402 DEBUG (MainThread) [pymadoka.connection] Starting connection manager on 1C:XX:XX:XX:XX:XX
2023-11-04 23:33:20.402 DEBUG (MainThread) [pymadoka.connection] Bluetooh LE hardware warming up...
2023-11-04 23:33:32.411 ERROR (MainThread) [pymadoka.connection] 
2023-11-04 23:33:32.412 DEBUG (MainThread) [pymadoka.connection] Reconnecting...
2023-11-04 23:33:44.421 ERROR (MainThread) [pymadoka.connection] 
2023-11-04 23:33:44.423 DEBUG (MainThread) [pymadoka.connection] Reconnecting...
2023-11-04 23:33:56.430 ERROR (MainThread) [pymadoka.connection] 
2023-11-04 23:33:56.431 DEBUG (MainThread) [pymadoka.connection] Reconnecting...
2023-11-04 23:34:08.440 ERROR (MainThread) [pymadoka.connection] 
2023-11-04 23:34:08.441 DEBUG (MainThread) [pymadoka.connection] Reconnecting...
2023-11-04 23:34:20.450 ERROR (MainThread) [pymadoka.connection] 
2023-11-04 23:34:20.451 DEBUG (MainThread) [pymadoka.connection] Reconnecting...
2023-11-04 23:34:32.460 ERROR (MainThread) [pymadoka.connection] 
2023-11-04 23:34:32.461 DEBUG (MainThread) [pymadoka.connection] Reconnecting...
2023-11-04 23:34:44.471 ERROR (MainThread) [pymadoka.connection] 
2023-11-04 23:34:44.472 DEBUG (MainThread) [pymadoka.connection] Reconnecting...
2023-11-04 23:34:56.480 ERROR (MainThread) [pymadoka.connection] 
2023-11-04 23:34:56.481 DEBUG (MainThread) [pymadoka.connection] Reconnecting...
2023-11-04 23:35:08.491 ERROR (MainThread) [pymadoka.connection] 
2023-11-04 23:35:08.492 DEBUG (MainThread) [pymadoka.connection] Reconnecting...
2023-11-04 23:35:11.840 INFO (MainThread) [pymadoka.connection] Connected to 1C:XX:XX:XX:XX:XX
2023-11-04 23:35:13.981 DEBUG (MainThread) [pymadoka.connection] Starting connection manager on F0:XX:XX:XX:XX:XX
2023-11-04 23:35:13.982 DEBUG (MainThread) [pymadoka.connection] Bluetooh LE hardware warming up...
2023-11-04 23:35:25.990 ERROR (MainThread) [pymadoka.connection] 
2023-11-04 23:35:25.991 DEBUG (MainThread) [pymadoka.connection] Reconnecting...
```

**Comment by mduran80** [comment]
I just pushed a small update, at least to prevent that HA hangs after a
reboot (mostly after an OS upgrade because it seems to “forget” all
pairings previously done to blueZ and it requires to repeat the steps to
pair with code). Until now, HA would stop loading until the device was
paired again with the code. At the same time, I fixed the “str” error.

I don’t have much time to maintain the integration but this error HAD to be
adressed. Anyway, I am still testing it but, although I had to leave, forst
tests seemed promising so I pushed. Just update code from repo.

Integration with internal bleak client would require more time. It was
added to HA much later than the integration was finished so code is not
ready for it.

**Comment by rawframe** [comment]
Thanks @mduran80
I updated the custom integration and now they all show up as unavailable in the dashboard. Before the update a restart would fix the issue temporarily. The 'str' error has gone and the recurring error now is:
```
2023-11-06 16:04:49.311 ERROR (MainThread) [pymadoka.connection] [org.bluez.Error.Failed] br-connection-canceled
2023-11-06 16:04:49.314 DEBUG (MainThread) [pymadoka.connection] Reconnecting...
```
Is this happening for anyone else? If so did deleting the integration and starting again solve it?

Thanks!

**Comment by mduran80** [comment]
You may need to pair the device again. Apparently, HA tries to reconnect at
some time in the future if a timeout happens (I am raising the timeout
error when we can’t connect to the thermostat now instead of hanging
forever) but the next attempt will fail again if the pairing has been lost.

It is unclear to me why the pairing is lost, it happens to me whenever I
update (next time I will update just HA or the SO to isolate the cause).
The integration appears as unavailable until you pair again using
bluetoothctl, but all settings should remain.

**Comment by rawframe** [comment]
@mduran80 
Thank you for the reply. Now working again  (I had to delete the integration and reinstall it).
What do you think of this script https://community.home-assistant.io/t/bluetooth-raspberry-pi-3-fails-after-some-time-and-does-not-recover/513684/30 ? I might try it but would rather wait for your next update. **Thanks again!**

**Comment by rawframe** [comment]
```2023-11-18 19:08:12.083 DEBUG (MainThread) [pymadoka.connection] Reconnecting...
2023-11-18 19:08:12.100 ERROR (MainThread) [pymadoka.connection] No backend with an available connection slot that can reach address XX:XX:XX:XX:XX:X0 was found
2023-11-18 19:08:12.101 DEBUG (MainThread) [pymadoka.connection] Reconnecting...
2023-11-18 19:08:12.104 ERROR (MainThread) [pymadoka.connection] No backend with an available connection slot that can reach address XX:XX:XX:XX:XX:XA was found
2023-11-18 19:08:12.105 DEBUG (MainThread) [pymadoka.connection] Reconnecting...
2023-11-18 19:08:23.859 INFO (MainThread) [pymadoka.connection] Disconnected XX:XX:XX:XX:XX:X0!
2023-11-18 19:08:23.865 DEBUG (MainThread) [pymadoka.connection] Starting connection manager on XX:XX:XX:XX:XX:X0
2023-11-18 19:08:23.891 ERROR (MainThread) [pymadoka.connection] [org.bluez.Error.Failed] Operation already in progress
2023-11-18 19:08:23.892 DEBUG (MainThread) [pymadoka.connection] Reconnecting...
2023-11-18 19:08:23.897 ERROR (MainThread) [pymadoka.connection] [org.bluez.Error.Failed] br-connection-canceled
2023-11-18 19:08:23.898 DEBUG (MainThread) [pymadoka.connection] Reconnecting...
2023-11-18 19:08:24.085 ERROR (MainThread) [pymadoka.connection]
2023-11-18 19:08:24.086 DEBUG (MainThread) [pymadoka.connection] Reconnecting...
2023-11-18 19:08:24.096 ERROR (MainThread) [pymadoka.connection]
2023-11-18 19:08:24.097 DEBUG (MainThread) [pymadoka.connection] Reconnecting...
2023-11-18 19:08:24.113 ERROR (MainThread) [pymadoka.connection]
2023-11-18 19:08:24.114 DEBUG (MainThread) [pymadoka.connection] Reconnecting...
2023-11-18 19:08:25.924 ERROR (MainThread) [pymadoka.connection] [org.bluez.Error.Failed] Operation already in progress
2023-11-18 19:08:25.925 DEBUG (MainThread) [pymadoka.connection] Reconnecting...
2023-11-18 19:08:25.938 ERROR (MainThread) [pymadoka.connection] [org.bluez.Error.Failed] br-connection-canceled
2023-11-18 19:08:25.939 DEBUG (MainThread) [pymadoka.connection] Reconnecting...
2023-11-18 19:08:27.956 ERROR (MainThread) [pymadoka.connection] [org.bluez.Error.Failed] Operation already in progress
2023-11-18 19:08:27.957 DEBUG (MainThread) [pymadoka.connection] Reconnecting...
2023-11-18 19:08:27.961 ERROR (MainThread) [pymadoka.connection] [org.bluez.Error.Failed] br-connection-canceled
2023-11-18 19:08:27.962 DEBUG (MainThread) [pymadoka.connection] Reconnecting...
```
I have to give up.... many years with no solution. At one point I thought it was because I was using pi3b internal bt, but i read this happens even with external dongles also from other users. There is another thread where someone has put this onto esp32 dev board and it kind of works if that helps anyone.

**Comment by 4lbertojordan** [comment]
Hi, I have tried this:

```bash
sudo usermod -G bluetooth -a $USER
```
```bash
uptime
 20:34:35 up 3 days,  9:49,  1 user,  load average: 0,30, 0,30, 0,34
 ```

I'm working with Raspberry pi 4, 4Gb with the last Raspbian version and the last commit of the master branch:
```bash
neofetch
       _,met$$$$$gg.          $USER@$HOST
    ,g$$$$$$$$$$$$$$$P.       --------------------
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 12 (bookworm) aarch64
 ,$$P'              `$$$.     Host: Raspberry Pi 4 Model B Rev 1.2
',$$P       ,ggs.     `$$b:   Kernel: 6.1.0-rpi6-rpi-v8
`d$$'     ,$P"'   .    $$$    Uptime: 3 days, 9 hours, 48 mins
 $$P      d$'     ,    $$P    Packages: 729 (dpkg)
 $$:      $$.   -    ,d$$'    Shell: bash 5.2.15
 $$;      Y$b._   _,d$P'      Resolution: 1920x1080
 Y$$.    `.`"Y$$$$P"'         Terminal: /dev/pts/0
 `$$b      "-.__              CPU: BCM2835 (4) @ 1.500GHz
  `Y$$                        Memory: 799MiB / 3792MiB
   `Y$$.
     `$$b.
       `Y$$b.
          `"Y$b._
              `"""
```

![image](https://github.com/mduran80/daikin_madoka/assets/8288699/c62d570d-24ad-483d-a1d2-834821940072)

**Comment by rawframe** [comment]
@4lbertojordan thank but im running pi3b image HASSIO so cannot use those commands. 
.. turning bluetoothctl off and on doesn't work either.

The integration has stopped working every day recently so unusable.
I'm going to try the esp32 version in the future ...it not my preference but maybe it works better.
https://community.home-assistant.io/t/daikin-madoka-brc1h-bluetooth-custom-component/268594/80
